# Default values for mongoshake-prometheus-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/osgurisdosre/mongoshake-prometheus-exporter
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

env:
  # Comma-separated list of MongoShake Prometheus Exporter endpoint list
  # For example, URL_LIST="http://host.docker.internal:9100/repl,http://host.docker.internal:9200/repl"
  URL_LIST: ""
  # The time interval at which the MongoShake Prometheus Exporter will query the URLs.
  SCRAPE_INTERVAL: 5

# You can pass the access key by envFromSecret, envFromSecrets or envFromConfigMaps
envFromSecret: ""

envFromSecrets: []
  # - name: secret-name
  #   optional: true

envFromConfigMaps: []
  # - name: configmap-name
  #   optional: true
  # - name: configmap2-name
  #   optional: true

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

serviceMonitor:
  ## If true, a ServiceMonitor CRD is created for a prometheus operator
  ## https://github.com/coreos/prometheus-operator
  ##
  enabled: false
  path: /metrics
  namespace: monitoring
  labels: {}
  interval: 10s
  scheme: http
  tlsConfig: {}
  scrapeTimeout: 10s
  relabelings: []
  metricRelabelings: []
  targetLabels: []
  selector: []

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
