name: Validate Pull Request

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  cpr:
    runs-on: ubuntu-latest
    steps:
      - name: Validates the pull request
        uses: Namchee/conventional-pr@v(version)
        with:
          access_token: "${{ secrets.REPO_TOKEN}}"